"""empty message

Revision ID: 1e11d3ba998a
Revises: 9f7c98267ef0
Create Date: 2020-05-08 15:29:49.715382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e11d3ba998a'
down_revision = '9f7c98267ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('specialization', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'specialization')
    # ### end Alembic commands ###