"""empty message

Revision ID: 63dc4ee8748a
Revises: 2d8cab9a28c2
Create Date: 2020-05-05 00:26:29.690250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63dc4ee8748a'
down_revision = '2d8cab9a28c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('master_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'master_id')
    # ### end Alembic commands ###
