"""empty message

Revision ID: 9f7c98267ef0
Revises: 63dc4ee8748a
Create Date: 2020-05-06 00:51:42.161835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7c98267ef0'
down_revision = '63dc4ee8748a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('choosen', sa.Boolean(), nullable=True),
    sa.Column('choosen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['choosen_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shedule_date_time'), 'shedule', ['date_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shedule_date_time'), table_name='shedule')
    op.drop_table('shedule')
    # ### end Alembic commands ###
